name: Build Android APK
run-name: Build Job

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com/aniyomiorg/aniyomi"
      imageLink:
        description: "The link of the image to use as the app icon"
        required: false
      appName:
        description: "New app name"
        required: false
      applicationId:
        description: "New application ID"
        required: false
      jdkVersion:
        description: "OpenJDK version to use: 8 / 11 / 17 etc."
        required: false
        default: "17"

jobs:
  build:
    runs-on: ubuntu-latest # Android SDK is built-in in this image
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ github.event.inputs.jdkVersion }}

      - name: Clone project
        run: git clone ${{ github.event.inputs.repository }} workspace

      - name: Install ImageMagick
        run: sudo apt-get install imagemagick

      - name: Modify build.gradle.kts
        run: |
          set -e
          cd workspace
          sed -i '/named("debug") {/i \
          getByName("release") { \n\
              signingConfig = signingConfigs.getByName("debug") \n\
          }' app/build.gradle.kts

      - name: Generate and Replace App Icons
        run: |
          set -e
          cd workspace
          if [ -n "${{ github.event.inputs.imageLink }}" ]; then
            wget -O icon.png ${{ github.event.inputs.imageLink }}
            rm app/src/main/res/mipmap-hdpi/ic_launcher.png
            rm app/src/main/res/mipmap-hdpi/ic_launcher_round.png
            rm app/src/main/res/mipmap-mdpi/ic_launcher.png
            rm app/src/main/res/mipmap-mdpi/ic_launcher_round.png
            rm app/src/main/res/mipmap-xhdpi/ic_launcher.png
            rm app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
            rm app/src/main/res/mipmap-xxhdpi/ic_launcher.png
            rm app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
            rm app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
            rm app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
            rm app/src/main/ic_launcher-web.png
            convert icon.png -resize 72x72 app/src/main/res/mipmap-hdpi/ic_launcher.png
            convert icon.png -resize 72x72 app/src/main/res/mipmap-hdpi/ic_launcher_round.png
            convert icon.png -resize 48x48 app/src/main/res/mipmap-mdpi/ic_launcher.png
            convert icon.png -resize 48x48 app/src/main/res/mipmap-mdpi/ic_launcher_round.png
            convert icon.png -resize 96x96 app/src/main/res/mipmap-xhdpi/ic_launcher.png
            convert icon.png -resize 96x96 app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
            convert icon.png -resize 144x144 app/src/main/res/mipmap-xxhdpi/ic_launcher.png
            convert icon.png -resize 144x144 app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
            convert icon.png -resize 192x192 app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
            convert icon.png -resize 192x192 app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
            convert icon.png -resize 400x400 app/src/main/ic_launcher-web.png
          fi

      - name: Zip project directory
        run: zip -r project.zip .

      - name: Upload project artifact
        uses: actions/upload-artifact@v2
        with:
          name: project-artifact
          path: project.zip
