name: Build Android APK
run-name: Build Job

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com/aniyomiorg/aniyomi"
      imageLink:
        description: "The link of the image to use as the app icon"
        required: false
      appName:
        description: "New app name"
        required: false
      applicationId:
        description: "New application ID"
        required: false
      jdkVersion:
        description: "OpenJDK version to use: 8 / 11 / 17 etc."
        required: false
        default: "17"
      taskName:
        description: "build.gradle task name: assemble[Flavor]Debug"
        required: false
        default: "assembleStandardRelease"

jobs:
  build:
    runs-on: ubuntu-latest # Android SDK is built-in in this image
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: ${{ github.event.inputs.jdkVersion }}

      - name: Clone project
        run: git clone ${{ github.event.inputs.repository }} workspace

      - name: Install ImageMagick
        run: sudo apt-get install imagemagick

      - name: Generate and Replace App Icons
        run: |
          set -e
          cd workspace
          if [ -n "${{ github.event.inputs.imageLink }}" ]; then
            wget -O icon.png ${{ github.event.inputs.imageLink }}
            rm app/src/main/res/mipmap-hdpi/ic_launcher.png
            rm app/src/main/res/mipmap-hdpi/ic_launcher_round.png
            rm app/src/main/res/mipmap-mdpi/ic_launcher.png
            rm app/src/main/res/mipmap-mdpi/ic_launcher_round.png
            rm app/src/main/res/mipmap-xhdpi/ic_launcher.png
            rm app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
            rm app/src/main/res/mipmap-xxhdpi/ic_launcher.png
            rm app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
            rm app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
            rm app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
            rm app/src/main/ic_launcher-web.png
            convert icon.png -resize 72x72 app/src/main/res/mipmap-hdpi/ic_launcher.png
            convert icon.png -resize 72x72 app/src/main/res/mipmap-hdpi/ic_launcher_round.png
            convert icon.png -resize 48x48 app/src/main/res/mipmap-mdpi/ic_launcher.png
            convert icon.png -resize 48x48 app/src/main/res/mipmap-mdpi/ic_launcher_round.png
            convert icon.png -resize 96x96 app/src/main/res/mipmap-xhdpi/ic_launcher.png
            convert icon.png -resize 96x96 app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
            convert icon.png -resize 144x144 app/src/main/res/mipmap-xxhdpi/ic_launcher.png
            convert icon.png -resize 144x144 app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
            convert icon.png -resize 192x192 app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
            convert icon.png -resize 192x192 app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
            convert icon.png -resize 400x400 app/src/main/ic_launcher-web.png
          fi

      - name: Change App Name
        run: |
          set -e
          cd workspace
          if [ -n "${{ github.event.inputs.appName }}" ]; then
            sed -i 's|<string name="app_name" translatable="false">.*</string>|<string name="app_name" translatable="false">${{ github.event.inputs.appName }}</string>|' i18n/src/commonMain/resources/MR/base/strings.xml
          fi

      - name: Change Application ID
        run: |
          set -e
          cd workspace
          if [ -n "${{ github.event.inputs.applicationId }}" ]; then
            sed -i 's|applicationId = ".*"|applicationId = "${{ github.event.inputs.applicationId }}"|' app/build.gradle.kts
          fi

      - name: Build APK
        working-directory: ./workspace
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew ${{ github.event.inputs.taskName }} --stacktrace

      - name: Count commits
        run: |
          set -e
          cd workspace
          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV

      - name: Upload APKs
        run: |
          set -e
          cd workspace
          apkTypes=("universal" "arm64-v8a" "armeabi-v7a" "x86" "x86_64")
          for apkType in "${apkTypes[@]}"; do
            apkPaths=(
              "./app/build/outputs/apk/standard/preview/app-standard-$apkType-preview.apk"
              "./app/build/outputs/apk/standard/debug/app-standard-$apkType-debug.apk"
              "./app/build/outputs/apk/standard/release/app-standard-$apkType-release-unsigned.apk"
              "./app/build/outputs/apk/dev/preview/app-dev-$apkType-preview.apk"
              "./app/build/outputs/apk/dev/debug/app-dev-$apkType-debug.apk"
              "./app/build/outputs/apk/dev/release/app-dev-$apkType-release-unsigned.apk"
            )
            for apkPath in "${apkPaths[@]}"; do
              if [ -f "$apkPath" ]; then
                apkName=$(basename "$apkPath" .apk)
                echo "Uploading $apkName..."
                echo "APK_PATH=$apkPath" >> $GITHUB_ENV
                echo "APK_NAME=$apkName-r${{ env.COMMIT_COUNT }}" >> $GITHUB_ENV
                echo "::endgroup::"
                break
              fi
            done
          done
        shell: bash


      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.APK_PATH }}
          name: ${{ env.APK_NAME }}.apk
          retention-days: 3
